### ISSUE TITLE
Availability of sources

### ISSUE THREAD

**Issue by anoff** [gnavvy/point-cloud-example#1]
Really love this use of deck.gl and wanted to check if it is possible for you to share the source codes as well instead of just the bundle?

I could go through the API docs but starting off an example is always a lot easier :)

**Comment by gnavvy** [comment]
@anoff Somehow I missed this message and sorry for the lãte reply.

We now have two examples of the point cloud rendering (laz and ply format) in the deck.gl repo.
https://github.com/uber/deck.gl/tree/4.1-release/examples/point-cloud-laz

Hope it helps.
